In [1]:
import numpy as np 
# creating an array
# array  is homogeneous in nature
arr = np.array([25,32,12,63,96,45,52.2,'karan'])
arr


array(['25', '32', '12', '63', '96', '45', '52.2', 'karan'], dtype='<U32')

In [7]:
print(type(arr))

<class 'numpy.ndarray'>


In [9]:
arr.dtype

dtype('<U32')

In [12]:
arr.ndim

1

In [13]:
arr

array(['25', '32', '12', '63', '96', '45', '52.2', 'karan'], dtype='<U32')

In [14]:
arr[3]

np.str_('63')

In [21]:
print(arr[-5])

63


In [16]:
arr[3:6]

array(['63', '96', '45'], dtype='<U32')

In [17]:
arr[3:6:2]

array(['63', '45'], dtype='<U32')

In [18]:
arr[4:7]

array(['96', '45', '52.2'], dtype='<U32')

In [20]:
arr[-4:-1]

array(['96', '45', '52.2'], dtype='<U32')

In [22]:
arr[1]="harshit"

In [23]:
arr

array(['25', 'harshit', '12', '63', '96', '45', '52.2', 'karan'],
      dtype='<U32')

In [24]:
arr1=np.arange(25)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [26]:
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
arr2.ndim

2

In [28]:
arr2[0]

array([1, 2, 3])

In [29]:
arr[0:2]

array(['25', 'harshit'], dtype='<U32')

In [30]:
arr2[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
arr2[0][2]

np.int64(3)

In [32]:
arr2[1:,1:]

array([[5, 6],
       [8, 9]])

In [33]:
arr2[-2:,-2:]

array([[5, 6],
       [8, 9]])

In [34]:
arr2[1:,0:2]

array([[4, 5],
       [7, 8]])

In [36]:
arr2[-2:,-3:-1]

array([[4, 5],
       [7, 8]])

In [39]:
arr2[-1][-1]=9
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
arr3=np.array([arr2,arr2,arr2])
arr3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [41]:
arr3.ndim

3

In [46]:
arr3[1,1:,1:]

array([[5, 6],
       [8, 9]])

In [47]:
arr3[0:,0,0:]

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [48]:
arr3[-3:,-3,-3:]

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [50]:
arr3[-3:,-3,::-1]

array([[3, 2, 1],
       [3, 2, 1],
       [3, 2, 1]])

In [51]:
arr3[0:,2,2]

array([9, 9, 9])

In [2]:
# day 2 of numpy
arr4=np.zeros(10)
arr4

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
arr4=np.zeros((5,4))
arr4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
arr4=np.zeros((5,4,3))
arr4

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [7]:
arr4=np.zeros((5,4,3,3))
arr4

array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],



In [9]:
arr4.shape

(5, 4, 3, 3)

In [11]:
arr4=np.ones((5,4))
arr4

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
arr=np.linspace(1,10,5)   # this function create an array in between the given number and giving how many numbers you want
arr

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [16]:
import random
random.randint(1,10)

3

In [15]:
random.random()  # this gives the random value in between the 0 to 1

0.28741775477936904

In [17]:
ls=['gagan','karan','harshit','jyoti','tishika']
random.choice(ls)

'gagan'

In [18]:
ls=['gagan','karan','harshit','jyoti','tishika']
random.choices(ls,k=2)

['jyoti', 'gagan']

In [19]:
random.shuffle(ls)
ls

['tishika', 'gagan', 'jyoti', 'karan', 'harshit']

In [ ]:
# np.random.randint
# np.random.random
#np.random.shuffle
#np.random.choice


In [21]:
arr=np.random.randint(1,50,10)
arr

array([ 1, 37, 47,  8,  6,  4, 45,  5, 17, 42], dtype=int32)

In [22]:
arr2=np.random.randint(1,50,(10,5))
arr2

array([[ 5, 16, 13, 27, 33],
       [20, 47,  9,  6,  6],
       [45,  7, 28, 33, 43],
       [33, 32, 22, 13, 16],
       [ 8, 46, 37, 19,  5],
       [45, 16, 32, 37, 23],
       [29, 45,  2, 34, 20],
       [ 1, 36, 42, 33, 45],
       [ 4, 32, 20, 25, 19],
       [19, 12, 39, 24, 16]], dtype=int32)

In [24]:
arr3=np.random.randint(100,200,(2,5,4))
arr3

array([[[169, 158, 109, 165],
        [121, 154, 194, 194],
        [159, 108, 167, 169],
        [145, 138, 156, 106],
        [154, 131, 182, 110]],

       [[156, 111, 199, 179],
        [190, 175, 170, 130],
        [171, 105, 123, 110],
        [136, 151, 185, 103],
        [158, 149, 100, 141]]], dtype=int32)

In [26]:
arr4 = np.random.randint(1,500,200)
arr4

array([126, 307,  31, 120,  49, 101, 156, 140, 385, 431,  85, 243,  98,
       287, 412,  75, 192, 165,  73, 242, 257, 235, 129,  35, 270, 208,
       303, 291, 185, 311, 437,   4,  40, 375, 498, 453, 238, 247, 145,
       477,  90,  11,  37, 281, 498, 397, 460, 292, 386, 413, 371,  98,
       293,  56, 202, 138, 428, 474, 438, 399, 244, 374, 339,   3, 466,
       280, 117,  24, 406, 335, 125, 335, 179, 353, 364, 422, 105, 483,
         5,  53, 279, 477,  80, 167, 223, 431, 338, 345, 337,  74, 333,
        23, 487, 473, 214, 181, 287, 364,   9, 340, 349, 209, 365, 384,
        79, 160, 416,  17, 249,  70,  77,  15, 328, 287,  18, 478, 375,
       191, 397, 222, 194, 226, 367, 211, 276, 139, 125, 336,  73,  40,
        92, 383, 398, 235, 182,  26, 492, 136, 134, 432, 381, 453, 209,
       146,  48, 401, 312, 283, 216, 207, 373,  70, 426, 334, 458, 477,
       212, 254,  58, 247,  94, 300,  49, 187, 456, 230, 352, 354, 460,
       285, 266,  64, 166, 124, 267, 108, 439,  58, 192, 477, 13

In [31]:
count=0
for i in arr4:
    if i<=100:
        count+=1
print(count)


43


In [42]:
count=0
for i in arr4:
    if i<=100 and i%2==0:
        count+=1
print(count)

22


In [44]:
arr4[arr4<=100]

array([31, 49, 85, 98, 75, 73, 35,  4, 40, 90, 11, 37, 98, 56,  3, 24,  5,
       53, 80, 74, 23,  9, 79, 17, 70, 77, 15, 18, 73, 40, 92, 26, 48, 70,
       58, 94, 49, 64, 58, 36,  9, 63, 32], dtype=int32)

In [45]:
arr5=arr4[arr4<=100]
arr5

array([31, 49, 85, 98, 75, 73, 35,  4, 40, 90, 11, 37, 98, 56,  3, 24,  5,
       53, 80, 74, 23,  9, 79, 17, 70, 77, 15, 18, 73, 40, 92, 26, 48, 70,
       58, 94, 49, 64, 58, 36,  9, 63, 32], dtype=int32)

In [46]:
arr5.size

43

In [51]:
arr=np.random.randint(1,50,(5,4))
arr

array([[ 4, 25, 33, 46],
       [ 7,  4, 43, 15],
       [19, 28, 35, 31],
       [ 6,  4, 32, 27],
       [24, 49, 42, 31]], dtype=int32)

In [55]:
arr 

array([[ 4, 25, 33, 46],
       [ 7,  4, 43, 15],
       [19, 28, 35, 31],
       [ 6,  4, 32, 27],
       [24, 49, 42, 31]], dtype=int32)

In [56]:
np.transpose(arr)

array([[ 4,  7, 19,  6, 24],
       [25,  4, 28,  4, 49],
       [33, 43, 35, 32, 42],
       [46, 15, 31, 27, 31]], dtype=int32)

In [57]:
np.transpose(arr).shape

(4, 5)

In [58]:
arr.T

array([[ 4,  7, 19,  6, 24],
       [25,  4, 28,  4, 49],
       [33, 43, 35, 32, 42],
       [46, 15, 31, 27, 31]], dtype=int32)

In [63]:
print(arr.min())       # aggregate function
print(arr.max())
print(arr.sum())
print(arr.mean())


4
49
505
25.25


In [75]:

print(np.argmin(arr))   # return the position of the minimum item
print(np.argmax(arr))

0
17


In [76]:
arr

array([[ 4, 25, 33, 46],
       [ 7,  4, 43, 15],
       [19, 28, 35, 31],
       [ 6,  4, 32, 27],
       [24, 49, 42, 31]], dtype=int32)

In [77]:
arr=np.array([8,7,9])
arr

array([8, 7, 9])

In [84]:
arr.sort()


In [81]:
arr[::-1]


array([9, 8, 7])

In [85]:
arr.argsort()

array([0, 1, 2])

In [86]:
arr*5

array([35, 40, 45])

In [87]:
arr+5

array([12, 13, 14])